# Generated by Django 4.2 on 2024-11-25 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0005_alter_product_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='materials',
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
